"""Turns the hand-written string tables into the two forms the game needs.

A module keeps its text in localization/<prefix>.<language>.txt, UTF-8, one
"$KEY<tab>text" line each.  Two things are made out of it:

  src/core/LocStrings.h                   the source language compiled into the
                                          plugin, so a missing file shows text
                                          rather than bare keys
  <out>/<Name>_<language>.txt             UTF-16LE, the format Skyrim itself
                                          reads from Interface/Translations

The second one is why the format was chosen.  The game resolves $-prefixed
strings in Papyrus and in menus out of that very file, so one file serves both
the window the plugin draws itself and the notifications the engine draws for
it - and a translation becomes an ordinary mod holding a single folder.

  python tools/build-localization.py                       into build/localization
  python tools/build-localization.py --out <dir>           somewhere else
  python tools/build-localization.py --no-header           files only

Nothing here is specific to Envoy: the module root, the name of the plugin and
the languages all come from arguments or from where the script sits.
"""

import argparse
import io
import os
import sys


def parse(path):
    """Reads one source table.  Returns [(key, value)] in file order."""
    rows = []
    seen = {}
    with io.open(path, "r", encoding="utf-8") as handle:
        for number, line in enumerate(handle, 1):
            line = line.rstrip("\r\n")
            if not line.startswith("$"):
                continue  # notes and blank lines
            if "\t" not in line:
                raise SystemExit("%s:%d: a key line needs a tab" % (path, number))
            key, value = line.split("\t", 1)
            if key in seen:
                raise SystemExit("%s:%d: %s is already set on line %d"
                                 % (path, number, key, seen[key]))
            seen[key] = number
            rows.append((key, value))
    return rows


def write_game_file(path, rows):
    """Skyrim reads translations as UTF-16LE with a byte order mark."""
    body = "".join("%s\t%s\r\n" % (key, value) for key, value in rows)
    with open(path, "wb") as handle:
        handle.write(b"\xff\xfe")
        handle.write(body.encode("utf-16-le"))


def escape(text):
    out = []
    for char in text:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        else:
            out.append(char)
    return "".join(out)


def write_header(path, rows, source_name):
    lines = [
        "#pragma once",
        "",
        "// GENERATED by tools/build-localization.py out of",
        "// localization/%s. Editing it here is pointless: the next run of the" % source_name,
        "// script overwrites the file. Edit the table instead.",
        "//",
        "// This is the baseline, not the text the player normally sees. The plugin",
        "// reads Interface/Translations first and falls back to these lines only when",
        "// the file is missing - which is the difference between a window full of",
        "// $ENVOY_* keys and a window somebody can still use.",
        "",
        "namespace Envoy",
        "{",
        "\tstruct LocString",
        "\t{",
        "\t\tconst char* key;",
        "\t\tconst char* text;",
        "\t};",
        "",
        "\tinline constexpr LocString kDefaultStrings[] = {",
    ]
    for key, value in rows:
        lines.append('\t\t{ "%s", "%s" },' % (escape(key), escape(value)))
    lines += ["\t};", "}", ""]
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", default=os.path.join(root, "localization"),
                    help="folder with the <prefix>.<language>.txt tables")
    ap.add_argument("--out", default=os.path.join(root, "build", "localization"),
                    help="folder to put the UTF-16 files in")
    ap.add_argument("--name", default="Envoy",
                    help="plugin name the game looks the files up by")
    ap.add_argument("--base", default="english",
                    help="source language: it is the one compiled in")
    ap.add_argument("--header", default=os.path.join(root, "src", "core", "LocStrings.h"),
                    help="where to put the compiled-in baseline")
    ap.add_argument("--no-header", action="store_true",
                    help="do not touch the baseline header")
    args = ap.parse_args()

    if not os.path.isdir(args.source):
        raise SystemExit("no string tables in " + args.source)

    prefix = args.name.lower() + "."
    tables = sorted(name for name in os.listdir(args.source)
                    if name.startswith(prefix) and name.endswith(".txt"))
    if not tables:
        raise SystemExit("no %s*.txt in %s" % (prefix, args.source))

    if not os.path.isdir(args.out):
        os.makedirs(args.out)

    made = []
    for name in tables:
        language = name[len(prefix):-len(".txt")]
        rows = parse(os.path.join(args.source, name))
        target = os.path.join(args.out, "%s_%s.txt" % (args.name, language))
        write_game_file(target, rows)
        made.append((language, len(rows)))

        if language == args.base and not args.no_header:
            write_header(args.header, rows, name)

    for language, count in made:
        sys.stdout.write("  %-10s %d strings\n" % (language, count))
    sys.stdout.write("  -> %s\n" % args.out)


if __name__ == "__main__":
    main()
