#pragma once

// GENERATED by tools/build-localization.py out of
// localization/envoy.english.txt. Editing it here is pointless: the next run of the
// script overwrites the file. Edit the table instead.
//
// This is the baseline, not the text the player normally sees. The plugin
// reads Interface/Translations first and falls back to these lines only when
// the file is missing - which is the difference between a window full of
// $ENVOY_* keys and a window somebody can still use.

namespace Envoy
{
	struct LocString
	{
		const char* key;
		const char* text;
	};

	inline constexpr LocString kDefaultStrings[] = {
		{ "$ENVOY_MENU_LOG", "Log" },
		{ "$ENVOY_LOG_TITLE", "Bridge log" },
		{ "$ENVOY_LOG_LEVEL", "How much to write" },
		{ "$ENVOY_LOG_SPEECH", "Write down recognised words" },
		{ "$ENVOY_LOG_SPEECH_HELP", "Off - the log keeps the utterance number and the model, but not the words.\\nOn - a transcript of everything said aloud stays on the disk." },
		{ "$ENVOY_LOG_SESSION_HELP", "Changes hold until the game is closed.\\nThe lasting value is the log.level and log.speechText keys\\nin Data/SKSE/Plugins/envoy/envoy.json." },
	};
}
