#pragma once

// GENERATED by tools/build-localization.py out of
// localization/speechbrokervoiceadapter.english.txt. Editing it here is pointless: the next run of the
// script overwrites the file. Edit the tables instead.
//
// This is the baseline, not the text a player normally sees. The module reads
// Interface/Translations first and falls back to these lines only when the file
// is missing - which is the difference between a window full of $SPEECHBROKER_* keys
// and a window somebody can still use.

#include "speechbroker-loc.h"

inline constexpr SpeechBrokerLoc::Entry kSpeechBrokerDefaultStrings[] = {
	{ "$SPEECHBROKERVOICE_WORD_I_AM_SOURCE", "I am the source" },
	{ "$SPEECHBROKERVOICE_WORD_I_AM_RESERVE", "I am in reserve" },
	{ "$SPEECHBROKERVOICE_WORD_DRAFT", "draft" },
	{ "$SPEECHBROKERVOICE_WORD_ACCURATE", "accurate" },
	{ "$SPEECHBROKERVOICE_WORD_SWITCHED_OFF", "switched off" },
	{ "$SPEECHBROKERVOICE_WORD_CAN_SPEAK", ", can speak" },
	{ "$SPEECHBROKERVOICE_WORD_NOTHING", "nothing" },
	{ "$SPEECHBROKERVOICE_WORD_SAID", "said" },
	{ "$SPEECHBROKERVOICE_WORD_DID_NOT_WORK", "did not work" },
	{ "$SPEECHBROKERVOICE_LOG_EXEC_OUTSIDE", "service: exec '{0}' leaves the folder of the adapter - I will not start it" },
	{ "$SPEECHBROKERVOICE_LOG_WORKDIR_OUTSIDE", "service: workingDir '{0}' leaves the folder of the adapter" },
	{ "$SPEECHBROKERVOICE_LOG_MODEL_NO_ID", "model out of {0}: no id key - skipping it" },
	{ "$SPEECHBROKERVOICE_LOG_MODEL_TWICE", "model {0} is declared twice: {1} and {2} - taking the first" },
	{ "$SPEECHBROKERVOICE_LOG_MODEL_BROKEN", "the model out of {0} did not parse: {1} - skipping it" },
	{ "$SPEECHBROKERVOICE_LOG_NO_SETTINGS", "no settings file: {0}" },
	{ "$SPEECHBROKERVOICE_LOG_SETTINGS_BROKEN", "the settings did not parse: {0}" },
	{ "$SPEECHBROKERVOICE_LOG_NOT_LOOPBACK", "the service at '{0}' does not point at this machine - I will not work" },
	{ "$SPEECHBROKERVOICE_LOG_PIECE_UNKNOWN", "model {0}: piece {1} was not found in the translation - its absorption will not reach the bridge" },
	{ "$SPEECHBROKERVOICE_LOG_MODEL_UNKNOWN", "the service returned an answer from model '{0}', which is not among the installed ones - taking it as final" },
	{ "$SPEECHBROKERVOICE_LOG_BRIDGE_REFUSED_UTTERANCE", "the bridge did not take the utterance from model {0}" },
	{ "$SPEECHBROKERVOICE_LOG_ABSORBS", "utterance {0} absorbs {1} earlier ones, completeness {2:.2f}" },
	{ "$SPEECHBROKERVOICE_LOG_SERVICE_ALREADY_UP", "the service is already up, connecting to it" },
	{ "$SPEECHBROKERVOICE_LOG_ANSWER_BROKEN", "the answer of the service did not parse - {0}" },
	{ "$SPEECHBROKERVOICE_LOG_BRIDGE_ROLE", "bridge: {0} ({1})" },
	{ "$SPEECHBROKERVOICE_LOG_VOCABULARY", "vocabulary of the subscribers: {0} phrases" },
	{ "$SPEECHBROKERVOICE_LOG_NOT_FOR_ME", "a request to {0} is not addressed to me" },
	{ "$SPEECHBROKERVOICE_LOG_REGISTER_REFUSED", "the bridge refused to register us" },
	{ "$SPEECHBROKERVOICE_LOG_REGISTERED", "registered at the bridge as {0}" },
	{ "$SPEECHBROKERVOICE_LOG_NO_MODELS", "not a single model is installed - there is nothing to recognise with. A model is installed as a separate mod and puts its listing into Data/SKSE/Plugins/speechbroker/adapters/voice/models" },
	{ "$SPEECHBROKERVOICE_LOG_MODEL", "model {0} ({1}) out of {2}: {3}{4}" },
	{ "$SPEECHBROKERVOICE_LOG_DECLARED", "models declared: {0}, declaring to the bridge: {1}" },
	{ "$SPEECHBROKERVOICE_LOG_BRIDGE_TOO_OLD", "the bridge is older than me: it understands contract version {0}, and I speak {1} - I will not work" },
	{ "$SPEECHBROKERVOICE_LOG_BRIDGE_NEWER", "the bridge is newer than me: contract version {0} against my {1} - working by mine, it will not ask me for the new fields" },
	{ "$SPEECHBROKERVOICE_LOG_INTERFACE_RECEIVED", "the interface of the bridge received, version {0}" },
	{ "$SPEECHBROKERVOICE_LOG_PLUGIN_LOADED", "{0} v{1} loaded" },
	{ "$SPEECHBROKERVOICE_LOG_NO_SETTINGS_FATAL", "I cannot work without settings" },
	{ "$SPEECHBROKERVOICE_LOG_SERVICE_SILENT_NO_START", "the service does not answer, and starting it is not allowed" },
	{ "$SPEECHBROKERVOICE_LOG_SERVICE_STARTING", "service: starting it - {0}" },
	{ "$SPEECHBROKERVOICE_LOG_SERVICE_IN_JOB", "service: not let out of the job (code {0}), starting it inside - MO2 will count the game as running for as long as it lives" },
	{ "$SPEECHBROKERVOICE_LOG_SERVICE_START_FAILED", "service: could not start it, code {0}" },
	{ "$SPEECHBROKERVOICE_LOG_SERVICE_UP", "the service is up" },
	{ "$SPEECHBROKERVOICE_LOG_SERVICE_TIMEOUT", "the service did not answer within the time allowed" },
	{ "$SPEECHBROKERVOICE_LOG_NO_SPEAKER", "speech {0}: not one installed model can speak" },
	{ "$SPEECHBROKERVOICE_LOG_SPOKE", "speech {0} by model {1}: {2}" },
};
